# Generated by Django 5.0.3 on 2024-03-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tutor', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('specie', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=30)),
            ],
        ),
    ]
