# Generated by Django 5.0.3 on 2024-04-17 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Entry Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exit Date'),
        ),
    ]
