# Generated by Django 5.0.3 on 2024-04-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_entry_date_product_exit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_withdrawn',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity Withdrawn'),
        ),
    ]
