# Generated by Django 5.0.3 on 2024-04-26 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_quantity_withdrawn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='exit_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_withdrawn',
        ),
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Create Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Update Date'),
        ),
    ]
