# Generated by Django 5.0.3 on 2024-05-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
