# Generated by Django 5.0.3 on 2024-05-24 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_id'),
        ('sales', '0003_alter_sale_id_alter_sale_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_price_sales', to='product.product', verbose_name='Unit Price'),
        ),
    ]
